const data = [
  {
    id: "17159",
    english: "yellow",
    transcription: "[ˈjeləʊ]",
    russian: "жёлтый",
    tags: "цвета",
    tags_json: '["u0446u0432u0435u0442u0430"]',
  },
  {
    id: "17160",
    english: "hedgehog",
    transcription: "[ˈheʤhɒg]",
    russian: "ёж",
    tags: "животные",
    tags_json: '["u0436u0438u0432u043eu0442u043du044bu0435"]',
  },
  {
    id: "17161",
    english: "dandelion",
    transcription: "[ˈdændɪlaɪən]",
    russian: "одуванчик",
    tags: "растения",
    tags_json: '["u0440u0430u0441u0442u0435u043du0438u044f"]',
  },
  {
    id: "17165",
    english: "inspiration",
    transcription: "[ɪnspɪˈreɪʃn]",
    russian: "вдохновение",
    tags: "noun",
    tags_json: '["noun"]',
  },
  {
    id: "17166",
    english: "hello",
    transcription: "[həˈləʊ]",
    russian: "привет",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "17168",
    english: "airplane",
    transcription: "[ˈerpleɪn]",
    russian: "самолет",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "17169",
    english: "program",
    transcription: "[ˈprəʊɡræm]",
    russian: "программа",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "17170",
    english: "justice",
    transcription: "[ˈdʒʌstɪs]",
    russian: "справедливость",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "17171",
    english: "variable",
    transcription: "[ˈverɪəbl]",
    russian: "переменная",
    tags: "",
    tags_json: '[""]',
  },
  {
    id: "17172",
    english: "jeans",
    transcription: "[dʒiːnz]",
    russian: "джинсы",
    tags: "одежда",
    tags_json: '["u043eu0434u0435u0436u0434u0430"]',
  },
  {
    id: "17173",
    english: "niece",
    transcription: "[niːs]",
    russian: "племянница",
    tags: "семья",
    tags_json: '["u0441u0435u043cu044cu044f"]',
  },
  {
    id: "17174",
    english: "day",
    transcription: "[deɪ]",
    russian: "день",
    tags: "время",
    tags_json: '["u0432u0440u0435u043cu044f"]',
  },
];

export default data;
